### ISSUE TITLE
Cannot find module 'ansi-diff-stream'

### ISSUE THREAD

**Issue by juliomatcom** [watson/progress-string#1]
I just installed this package and when I run `node example.js` it throws the bellow error for the missing module. Please add 'ansi-diff-stream' to the package.json. After added works fine.

node example.js 
module.js:442
    throw err;
    ^

Error: Cannot find module 'ansi-diff-stream'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/juliomatcom/Apps/bar/node_modules/progress-string/example.js:4:12)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)

**Comment by juliomatcom** [comment]
Ahh sorry is fine like that, it is not a dependency of the package, just the example :)

**Comment by watson** [comment]
@juliomatcom I can see the confusion. I've now added `ansi-diff-stream` as a devDependency so it's a little easier to play with if you clone the repo 😃
